### ISSUE TITLE
Angular 譯成"角度"的建議

### ISSUE THREAD

**Issue by linmasaki** [dotnet/AspNetCore.Docs.zh-tw#142]
您好，想提供一些建議，此[連結](https://docs.microsoft.com/zh-tw/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#general-description-of-the-angular-app)的地方，角度應用程式的角度是否改成 Angular 會比較適當，文中還有很多地方也都翻成角度，閱讀起來蠻不直覺的，謝謝!

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [ASP.NET Core 上單一頁面應用程式的驗證簡介](https://docs.microsoft.com/zh-tw/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @linmasaki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
您好，@linmasaki，

謝謝您的寶貴意見。問題中提及的頁面使用了機器翻譯，因此內容可能未必能夠完全理解。我們最近在右側新增了 [Read in English] (在英文版中閱讀) 選項，可讓您切換至英文版本而不需要變更語言設定。

順頌時祺
Microsoft DOCS 國際小組
