### ISSUE TITLE
case-insensitive 翻譯錯誤

### ISSUE THREAD

**Issue by kkbruce** [dotnet/AspNetCore.Docs.zh-tw#143]
原文：Text matching is **case-insensitive** and based on the decoded representation of the URLs path.
譯文：文字比對會區分大小寫，並以 URL 路徑的已解碼表示法為基礎。
應該翻譯為「不區分大小寫」而不是「區分大小寫」。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [ASP.NET Core 中的路由](https://docs.microsoft.com/zh-tw/aspnet/core/fundamentals/routing?view=aspnetcore-3.1&source=docs#route-template-reference)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @kkbruce
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
`Original`: Text matching is case-insensitive and based on the decoded representation of the URLs path.

`Translation`: Text matching is case sensitive and is based on the decoded representation of URL paths.

Should be translated as "case insensitive" rather than "case sensitive".

**Comment by CeciAc** [comment]
@kkbruce 您好： 
 
感謝您的參與。 
  
目前不接受參與機器翻譯內容的翻譯問題。 
 
我們很重視您對人工翻譯內容的意見反應與建議，並使用這些意見來訓練機器翻譯引擎，因此，您的貢獻內容會隨著時間改善人工與機器翻譯的品質。 
 
您可以根據各個內容檔案標頭的 ms.translationtype 中繼資料值 “HT”，分辨出人工翻譯的主題，其他則是機器翻譯的主題 (值為 “MT” 代表機器翻譯)。 

非常感謝您的支援。 

Microsoft DOCS 全球體驗小組

**Comment by kkbruce** [comment]
Hi @CeciAc 

如 @Rick-Anderson  所說，這是"翻譯錯誤"而不是"翻譯問題"。如果連錯誤都不修正，這樣不太好了吧？

As @Rick-Anderson said, this is "translation error" rather than "translation problem". If you don't fix your mistakes, isn't that good?
