### ISSUE TITLE
「系結」應該是「繫結」 

### ISSUE THREAD

**Issue by kkbruce** [dotnet/AspNetCore.Docs.zh-tw#144]
文中多處使用錯誤的「系結」一詞，正確應該是「繫結」 

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [ASP.NET Core 中的資料繫結](https://docs.microsoft.com/zh-tw/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @kkbruce
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The wrong word "binding" is used in many places in the text.

@CeciAc
This looks like a translation error to me.

**Comment by Rick-Anderson** [comment]
@kkbruce 
您是說“裝訂”一詞翻譯錯誤嗎？

**Comment by kkbruce** [comment]
![example](https://user-images.githubusercontent.com/2024682/78530307-fea39080-7815-11ea-908f-6575c8c5fe90.png)

"binding" should be translated as  "繫結" not "系結". There are many translation errors in the text.

**Comment by CeciAc** [comment]
Hello @kkbruce

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
