### ISSUE TITLE
Wrong translation title

### ISSUE THREAD

**Issue by u8989332** [dotnet/AspNetCore.Docs.zh-tw#146]
English: Use cookie authentication without ASP.NET Core Identity

Current translation: 在 cookie 不 ASP.NET Core 的情況下使用驗證Identity

Revised translation: 使用沒有ASP.NET Core Identity的 Cookie 驗證

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [在 cookie 不 ASP.NET Core 的情況下使用驗證Identity](https://docs.microsoft.com/zh-tw/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We've already fixed this in https://github.com/dotnet/AspNetCore.Docs/pull/19446
 It should  appear in each language in the next 3 days.

Please close.
