### ISSUE TITLE
Wrong translation title

### ISSUE THREAD

**Issue by u8989332** [dotnet/AspNetCore.Docs.zh-tw#147]
English: Use social sign-in provider authentication without ASP.NET Core Identity

Current translation: 使用不 ASP.NET Core 的社交登入提供者驗證Identity

Revised translation: 使用沒有ASP.NET Core Identity的社交登入提供者驗證

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 6f9d7ad5-47d6-80bf-88fe-fac3a74151a3
* Version Independent ID: e64816f4-3391-5aab-31c2-ab4f915bc7f6
* Content: [不 ASP.NET Core 的 Facebook、Google 及外部提供者驗證Identity](https://docs.microsoft.com/zh-tw/aspnet/core/security/authentication/social/social-without-identity?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/social-without-identity.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/security/authentication/social/social-without-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @guardrex @scottaddie 
 @JasonCard  please transfer this issue to https://github.com/dotnet/AspNetCore.Docs/issues and I'll add `Identity` to the no loc list. It's always uppercase.

**Comment by Rick-Anderson** [comment]
Actually it looks like it's not translating Identity and that's what we want.
@u8989332  `Identity` is a product and shouldn't be translated. Why do you think it should be translated?

**Comment by u8989332** [comment]
@Rick-Anderson  The subject `ASP.NET Core Identity` is a major library so it should be bundled together, not separate.

**Comment by Rick-Anderson** [comment]
@u8989332  I see now


Current translation:: Use a social login provider that is not ASP.NET Core to verify Identity

Revised translation: Use social login provider authentication without ASP.NET Core Identity

Maybe we need no loc: ASP.NET Core Identity,

**Comment by u8989332** [comment]
@Rick-Anderson  Yes, the English current translation means I mention the semantic problem with Traditional-Chinese. 

#146 is the same problem.

**Comment by JasonCard** [comment]
@u8989332 Thank you for reporting this issue.

@Rick-Anderson Transferred this issue to [https://github.com/dotnet/AspNetCore.Docs/issues/19462](https://github.com/dotnet/AspNetCore.Docs/issues/19462) and closing this one. Thank you for your help to lock this term from localization.
